packages:
  - 'packages/*'
  - '!packages/solid-router-copy'
  - 'examples/react/*'
  - 'examples/react/router-monorepo-react-query/packages/*'
  - 'examples/react/router-monorepo-simple/packages/*'
  - 'examples/react/router-monorepo-simple-lazy/packages/*'
  - 'e2e/react-router/*'
  - 'e2e/start/*'
